[nm]
  [nm.expiry]
    interval = "5s"

[keyhole]
  configkey="password"
  servers = [
    "127.0.0.1:1234"
  ]

[[Network]]
Name = "Default Network"
ID = "default"
Interface = "wg0"
ApproveExpiry = "1m"
ActivateExpiry = "30s"
IPAM = [
  "dummy",
]
AllowedIPs = [
  "10.0.0.0/23"
]
DNS = [
  "8.8.8.8",
]

[[Network]]
Name = "Another Network"
ID = "anet"
Interface = "wg1"
ApproveMode = "AUTO"
IPAM = [
  "dummy",
]

[[Network]]
Name = "ChaosNet"
ID = "chaos"
Interface = "wg2"
ApproveMode = "AUTO"
ActivateMode = "AUTO"
