[nm]
  [nm.expiry]
    interval = "5s"
  [nm.ipam.linearv4]
    [nm.ipam.linearv4.standard]
      cidr = "192.168.32.0/24"
      dns = ["1.1.1.1"]
      search = ["example.com"]
      reserved = ["192.168.32.1/32"]

[keyhole]
  configkey="password"
  servers = [
    "127.0.0.1:1234"
  ]

[http]
  [http.token]
    lifetime = "10m"
    key = "asdfasdfasdfasdf"

[[Network]]
Name = "Default Network"
ID = "default"
Interface = "wg0"
ApproveExpiry = "1m"
ActivateExpiry = "30s"
IPAM = [
  "dummy:dummy",
  "linearv4:standard",
]
AllowedIPs = [
  "10.0.0.0/23"
]
DNS = [
  "8.8.8.8",
]

[[Network]]
Name = "Another Network"
ID = "anet"
Interface = "wg1"
ApproveMode = "AUTO"
IPAM = [
  "dummy:dummy",
]

[[Network]]
Name = "ChaosNet"
ID = "chaos"
Interface = "wg2"
ApproveMode = "AUTO"
ActivateMode = "AUTO"
